services:
    lysand:
        image: ghcr.io/lysand-org/lysand:latest
        volumes:
            - ./logs:/app/dist/logs
            - ./config:/app/dist/config
            - ./uploads:/app/dist/uploads
            - ./glitch:/app/dist/glitch
        restart: unless-stopped
        container_name: lysand
        command: "cli start --all-threads"
        networks:
            - lysand-net
        depends-on:
            - db
            - redis
            - meilisearch
            - fe
    
    fe:
        image: ghcr.io/lysand-org/lysand-fe:main
        container_name: lysand-fe
        restart: unless-stopped
        networks:
            - lysand-net
        environment:
            NUXT_PUBLIC_API_HOST: https://yourserver.com
            
    db:
        image: ghcr.io/lysand-org/postgres:main
        container_name: lysand-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: lysand
            POSTGRES_USER: lysand
            POSTGRES_PASSWORD: _______________
        networks:
            - lysand-net
        volumes:
            - ./db-data:/var/lib/postgresql/data

    redis:
        image: redis:alpine
        container_name: lysand-redis
        volumes:
            - ./redis-data:/data
        restart: unless-stopped
        networks:
            - lysand-net

    meilisearch:
        stdin_open: true
        environment:
            - MEILI_MASTER_KEY=__________________
        tty: true
        networks:
            - lysand-net
        volumes:
            - ./meili-data:/meili_data
        image: getmeili/meilisearch:v1.7
        container_name: lysand-meilisearch
        restart: unless-stopped

networks:
    lysand-net: