services:
    lysand:
        image: ghcr.io/lysand-org/lysand:latest
        volumes:
            - ./logs:/app/dist/logs
            - ./config:/app/dist/config
            - ./uploads:/app/dist/uploads
            - ./glitch:/app/dist/glitch
        restart: unless-stopped
        container_name: lysand
        command: "cli start --all-threads"
        networks:
            - lysand-net
        depends_on:
            - db
            - redis
            - sonic
            - fe
    
    fe:
        image: ghcr.io/lysand-org/lysand-fe:main
        container_name: lysand-fe
        restart: unless-stopped
        networks:
            - lysand-net
        environment:
            NUXT_PUBLIC_API_HOST: https://yourserver.com
            
    db:
        image: ghcr.io/lysand-org/postgres:main
        container_name: lysand-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: lysand
            POSTGRES_USER: lysand
            POSTGRES_PASSWORD: _______________
        networks:
            - lysand-net
        volumes:
            - ./db-data:/var/lib/postgresql/data

    redis:
        image: redis:alpine
        container_name: lysand-redis
        volumes:
            - ./redis-data:/data
        restart: unless-stopped
        networks:
            - lysand-net

    sonic:
        volumes:
          - ./config.cfg:/etc/sonic.cfg
          - ./store/:/var/lib/sonic/store/
        image: valeriansaliou/sonic:v1.4.9
        container_name: lysand-sonic
        restart: unless-stopped
        networks:
            - lysand-net

networks:
    lysand-net: