name: Staging build bundle

on:
  push:
    branches: ["staging"]

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install NPM packages
        run: |
          bun install

      - name: Bundle
        run: |
          mkdir bundle
          cp dist/ config/ CODE_OF_CONDUCT.md CONTRIBUTING.md README.md flake.nix shell.nix flake.lock docs/ LICENSE SECURITY.md bundle/

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: staging-dist
          path: bundle/
